### ISSUE TITLE
Can't apply a query to the master index

### ISSUE THREAD

**Issue by maksymilian-majer** [firebase/firebase-util#28]
I've tried applying query to the `ref` passed as argument to the `NormalizedCollection` and to the the `NormalizedRef`. In both cases I don't get any results.

Here are two plunks that illustrate this:
* Applying query to master index: http://plnkr.co/edit/max7TciVx48YG3cNcfpS
* Applying query to `NormalizedRef`: http://plnkr.co/edit/5AtkOtfvBorKkLnLCHAw

**Comment by katowulf** [comment]
Because of this console error:

Error: Each argument to the NormalizedCollection constructor must be a valid Firebase reference or an Array containing a Firebase ref as the first argument
    at assertPaths (firebase-util.js:696)
    at Object.NormalizedCollection (firebase-util.js:644)
    at new <anonymous> (script.js:8)
    at Object.e [as invoke] (angular.min.js:37)
    at G.instance (angular.min.js:76)
    at angular.min.js:59
    at r (angular.min.js:7)
    at J (angular.min.js:59)
    at g (angular.min.js:52)
    at angular.min.js:51

**Comment by maksymilian-majer** [comment]
This console error is in the first case and it's pretty clear that I can't apply query on the Firebase reference before passing it to the `NormalizedCollection`. I also tested applying query to the `NormalizedRef` which is returned by calling `ref()` on the `NormalizedCollection`. I concluded that it's possible from the docs (https://github.com/firebase/firebase-util/blob/master/src/NormalizedCollection/README.md#query-methods).

This is demonstrated here: http://plnkr.co/edit/5AtkOtfvBorKkLnLCHAw
You'll see in the console that `on('value',...)` results in `null` being logged to the console.

**Comment by katowulf** [comment]
No disagreement here, just adding context with the console error.

**Comment by maksymilian-majer** [comment]
In that case here's the console warning from firebase-util from the second example:

    FIREBASE WARNING: Exception was thrown by user callback. TypeError: undefined is not a function
        at AbstractRecord.child (https://cdn.firebase.com/libs/firebase-util/0.2.2/firebase-util.js:229:26)
        at Object.RecordList.add (https://cdn.firebase.com/libs/firebase-util/0.2.2/firebase-util.js:2099:24)
        at Object.RecordSetEventManager._add (https://cdn.firebase.com/libs/firebase-util/0.2.2/firebase-util.js:2078:18)
        at h.Mb (https://cdn.firebase.com/js/client/2.2.1/firebase.js:52:375)
        at Ab (https://cdn.firebase.com/js/client/2.2.1/firebase.js:47:165)
        at wb (https://cdn.firebase.com/js/client/2.2.1/firebase.js:22:216)
        at xb (https://cdn.firebase.com/js/client/2.2.1/firebase.js:21:1261)
        at Bh.h.Cd (https://cdn.firebase.com/js/client/2.2.1/firebase.js:194:472)
        at kh.h.Bd (https://cdn.firebase.com/js/client/2.2.1/firebase.js:182:266)
        at Zg.Bd (https://cdn.firebase.com/js/client/2.2.1/firebase.js:174:364)

Hope this will be helpful.

**Comment by katowulf** [comment]
Looks like this is because we call .child() on the query ref. Need to .ref().child() that.

**Comment by michaeldim** [comment]
I am trying to apply a query on the master index using the orderByValue() method however with the 2.2.4 release I am getting an 'undefined is not a function' error, http://plnkr.co/edit/HaA1lz

**Comment by bogdantmm92** [comment]
''' [Error] Error: Each argument to the NormalizedCollection constructor must be a valid Firebase reference or an Array containing a Firebase ref as the first argument '''

I only have this problem on mobile devices. Any idea why?

**Comment by katowulf** [comment]
@bogdantmm92 I've deleted your comment as it has nothing to do with this issue. Please submit a separate issue in the tracker, and be sure to include an [mcve](http://stackoverflow.com/help/mcve) than demonstrates how you've arrived at the error. ☼, Kato
